### ISSUE TITLE
why is it AAA{T} Array{Array{Array{T,1},1},1} and not Array{T,3}?

### ISSUE THREAD

**Issue by floswald** [alancrawford/Smolyak#5]
i was just wondering why do define those things this way. is there any reason? it looks a bit weird when i print out the grid points to have all of those ragged arrays hanging around. just asking.

**Comment by alancrawford** [comment]
I had a couple of reasons - which may  reflect my failings as much as anything else. 

Firstly, I found that passing, say X[i][j] where X::AAA{T} rather than X1[i,j,:] where X::Array{T,3} was much more efficient in terms of speed and memory used.  Maybe this less of a concern in new versions of Julia…. 

Secondly, in the application I want to have grids of different sizes - hence the ragged arrays.
